[project]
name = 'Lending-Platform-Protocol'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.Lending-Platform-Protocol]
path = 'contracts/Lending-Platform-Protocol.clar'
clarity_version = 2
epoch = 2.5

[contracts.collateral-management]
path = 'contracts/collateral-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.interest-rate-model]
path = 'contracts/interest-rate-model.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
